# Reference: <https://blog.samplasion.js.org/build-jekyll-with-custom-plugins-on-github-pages>
# see bug <https://github.com/thenewobjective/thenewobjective.github.io/issues/55>

name: Jekyll Deploy

on:
  push:
    branches: [ master ]
    paths-ignore:
      '._drafts/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      '._drafts/**'
  schedule:
    - cron: "0 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v1
      - name: Bundler Cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Build & Deploy to GitHub Pages
        uses: joshlarsen/jekyll4-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
